### ISSUE TITLE
flickity-prev-next-button should also change slide in main slider

### ISSUE THREAD

**Issue by hirasso** [metafizzy/flickity-as-nav-for#2]
Good morning from Berlin! 

Yesterday I tried out the asNavFor functionality and noticed that the flickity-prev-next buttons on the navigation slider don't have any effect on the main slider. Is this intended behaviour? Intuitively I thought it should always select the same item in the main slider as in the navigation slider.

**Comment by desandro** [comment]
Thanks for reporting this issue. Turns out, this behavior is intended. By not selecting the main slider when clicking the prev/next buttons or dragging the nav slider, users can move around the nav slider without changing the main slider.

If you do you want sync both the nav and main sliders, try using [flickity-sync](https://github.com/metafizzy/flickity-sync)

**Comment by hirasso** [comment]
flickity-sync looks exactly like the thing I was looking for.

Best support for the best slider in the internet. Thank you so much.
